services:

  api:
    # Constrói a imagem a partir do Dockerfile no diretório atual ('.')
    build: .
    container_name: api
    # Mapeia a porta 8000 do seu computador para a porta 8000 do contêiner
    ports:
      - "8000:8000"
    # Monta o diretório atual no diretório /app do contêiner.
    # Isso permite que as alterações no código sejam refletidas imediatamente (hot-reload)
    # e também garante que o banco de dados 'escola.db' seja salvo no seu computador.
    volumes:
      - .:/app
    # Comando para iniciar a aplicação com Uvicorn, permitindo acesso externo e hot-reload.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

